feature: differentiate commit formats between trunks and branches

diff --git a/validate-new-commit-messages/action.yaml b/validate-new-commit-messages/action.yaml
--- a/validate-new-commit-messages/action.yaml
+++ b/validate-new-commit-messages/action.yaml
@@ -1,16 +1,23 @@
 name: Validate new commit messages
 description: This action validates the format of commit messages for commits added since the last push.
 
+inputs:
+  trunk:
+    description: Is this being run on mainline branches?
+    default: "true"
+
 runs:
   using: composite
   steps:
-    - name: Validate
+    - name: Validate trunks
+      if: ${{ inputs.trunk === 'true' }}
       run: |
         # Equivalent to `git log ORIG_HEAD..HEAD`.
         # `github.event.before` is the last commit SHA before the push.
+
         git log --format=%s ${{ github.event.before }}..${{ github.sha }} | while read -r line; do
           echo "Validating commit message: '$line'"
-          if [[ ! $line =~ ^((constraint|experiment|feature|fix|maintenance|merge|refactor|release): [a-z].*)$ ]]; then
+          if [[ ! $line =~ ^((constraint|feature|fix|maintenance|refactor|release): [a-z].*)$ ]]; then
             echo "Invalid commit message: '$line'"
             exit 1
           fi
@@ -19,5 +26,15 @@ runs:
             exit 1
           fi
         done
-      # For custom actions, unlike workflows, we do need to specify the shell for run commands:
+      shell: bash
+    - name: Validate branches
+      if: ${{ inputs.trunk === 'false' }}
+      run: |
+        git log --format=%s ${{ github.event.before }}..${{ github.sha }} | while read -r line; do
+          echo "Validating commit message: '$line'"
+          if [[ ! $line =~ ^((experiment|merge|wip): [a-z].*)$ ]]; then
+            echo "Invalid commit message: '$line'"
+            exit 1
+          fi
+        done
       shell: bash
